### ISSUE TITLE
beautifier

### ISSUE THREAD

**Issue by blonkm** [syncfiddle/syncfiddle-issues#1]
It would be a great idea to incorporate a code beautfier (simply indent properly). I don't know if this is already part of Emmet, but there are plenty of plugins I presume (js-beautify, prettier).

**Comment by polygonplanet** [comment]
@blonkm Sorry for replying so late.
Does your idea mean that is an automatic indent in SyncFiddle code editor by using js-beautify or prettier plugins? (For example adding "Indent" button in the header.)

**Comment by blonkm** [comment]
Have a look at how repl.it does this in HTML and JavaScript.

**Comment by polygonplanet** [comment]
We'll considering features for beautfier (HTML, CSS, JS). This issue will close once.
