### ISSUE TITLE
pressing the run button doesn't delete previous "run"

### ISSUE THREAD

**Issue by chase-moskal** [syncfiddle/syncfiddle-issues#2]
love syncfiddle, it's the best way to sketch out javascript ideas collaboratively

i've found that if i use `setInterval` to log timestamps to the console, and then i comment out the functionality and press "run" again, the console is still being bombarded by timestamps from the previous session

that is, despite no longer having any `console.log` calls, the console is still receiving logs from the previous "run"

the workaround i found, was to refresh the page before each and every "run" operation

**Comment by polygonplanet** [comment]
I checked this problem, and the previous `setInterval` timer running like the zombie process when pushing "run" button.
Thank you for the great report! We will deal with this issue in the future.

**Comment by polygonplanet** [comment]
We fixed this problem. Now, SyncFiddle editor clears all setInterval and setTimeout timers when the Run button pushed. If you don't work, please try to clear the browser cache.
Thanks your report! 👍
