### ISSUE TITLE
Line number not correct when displaying error

### ISSUE THREAD

**Issue by Abhay07** [syncfiddle/syncfiddle-issues#3]
When there is an error in code, the line number is not correct.

For example - In the attached screenshot error is in line number 18, but says 15:45:48.608 in console, which is not clear.
![Screenshot 2020-02-19 at 3 45 59 PM](https://user-images.githubusercontent.com/11444452/74824908-feffcf00-532e-11ea-99bd-f8afd1ba5f61.png)

**Comment by polygonplanet** [comment]
This is not line number, 15:45:48.608 means `hours:minutes:seconds.milliseconds`.
We'll considering to show line numbers. thanks!
