### ISSUE TITLE
display:flex behaves differently in chrome and flex in syncfiddle

### ISSUE THREAD

**Issue by Abhay07** [syncfiddle/syncfiddle-issues#5]
I'm running same code run in chrome and firefox with **display flex**, see how the div is centered in Firefox but not in Chrome. Ideally it should behave consistently in both browser and correct behaviour is of Firefox.

Chrome screenshot
![Screenshot 2020-02-19 at 3 51 32 PM](https://user-images.githubusercontent.com/11444452/74825436-ee9c2400-532f-11ea-86a4-13acec13188d.png)

Firefox screenshot
![Screenshot 2020-02-19 at 3 51 19 PM](https://user-images.githubusercontent.com/11444452/74825466-feb40380-532f-11ea-90c3-8afbf74c847e.png)

**Comment by polygonplanet** [comment]
Oh... this problem may be a parent iframe element, or the difference between the CSS implementations of Chrome and Firefox may be the cause. We recommend Chrome for use. Can you try using Chrome for now?
Thanks for your point out!
